
@gameid = 58a8978a-6f6d-47b4-a608-8018485e0b8f

###
POST https://localhost:5001/game/newgame/ HTTP/1.1
content-type: application/json

{
    "width": 40,
    "height": 30,
    "numberOfMines": 40
}

###

GET https://localhost:5001/game HTTP/1.1

### 

GET https://localhost:5001/game/{{gameid}}
###

POST https://localhost:5001/game/{{gameid}} HTTP/1.1
content-type: application/json

{
    "ActionType": "explore",
    "X": 10,
    "Y": 10
}

###

POST https://localhost:5001/game/{{gameid}} HTTP/1.1
content-type: application/json

{
    "actionType": "quit"
}